services:
  app:
    build:
      target: dev
    volumes:
      - .:/opt/project/
      - node_modules:/opt/project/node_modules
    ports:
      - "9200:9200"
  postgres:
    ports:
      - "5432:5432"

volumes:
  node_modules:
