services:
  app:
    depends_on:
      - postgres
    env_file: .env
    environment:
      - WAIT_HOSTS=postgres:5432
      - NODE_ENV
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    user: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
volumes:
  postgresql-data:
