services:
  app:
    build:
      target: base
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      - WAIT_HOSTS=postgres:5432
      - NODE_ENV
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    user: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 0.5s
      timeout: 5s
      retries: 5
volumes:
  postgresql-data:
